version: '3.7'
services:
  elasticsearch01:
    build: ./es
    container_name: elasticsearch01
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./es/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9201:9200
    networks:
      - esnet

  kibana01:
    build: ./kibana
    container_name: kibana01
    links:
      - elasticsearch01:elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/elasticsearch/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata01:
    driver: local

networks:
  esnet:
